---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "01/28/2021"
quarter <- "Winter2021"
week_folder <- "01-28_Foucault-Welles"
title <- "#HashtagActivism: Networks of Race and Gender Justice"
speaker <- "Brooke Foucault Welles"
department <- "Department of Communication"
university <- "Northeastern University"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2021/issues/3"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJYucOiupjsiH9IxcgGF54C_Q5O2sb2UU2WA"
#Papers
week_paper_ref1 <- "Jackson, S. J., & Foucault Welles, B. (2015). Hijacking# myNYPD: Social media dissent and networked counterpublics. Journal of Communication, 65(6), 932-952."
week_paper_file1 <- "2015_Jackson_Welles_myNYPD.pdf"

week_paper_ref2 <- "Gallagher, R. J., Stowell, E., Parker, A. G., & Foucault Welles, B. (2019). Reclaiming stigmatized narratives: The networked disclosure landscape of# MeToo. Proceedings of the ACM on Human-Computer Interaction, 3(CSCW), 1-30."
week_paper_file2 <- "2019-gallagher_metoo_cscw.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")
readings2 <- paste0("[", week_paper_ref2,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file2,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>


<p class=footertext2>

**Summary:** The proliferation of social media has given rise to widespread study and speculation about the impact of digital technologies on politics, activism, and social change. Key among these debates is the role social media play in shaping the contemporary public sphere, and by proxy, our societies. Maligned by some as “slacktivism,” I will argue social media platforms such as Twitter create unique opportunities for often-excluded voices to challenge the terms of public debate. Using the evidence from Twitter hashtag networks such as #BlackLivesMatter and #MeToo, I will demonstrate how hashtag activism complements other forms of activism to change the terms of mainstream public debates about race and gender justice in the United States. 


</p>

<br>
<p class=footertext2>
**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>
<br>
<br>
<p class=footertext2>

**Brooke Foucault Welles** is an Associate Professor in the Department of Communication Studies and a core faculty member of the Network Science Institute at Northeastern University. Combining the methods of computational social science and network science with the theories of communication studies, Foucault Welles studies how online communication networks enable and constrain behavior, with particular emphasis on how these networks enable the pursuit of individual, team, and collective goals.

Much of her work is interdisciplinary and collaborative, with co-authors from computer science, political science, digital humanities, design, and public health. Her recent contributions include a series of studies of the transformative power of networked counterpublics, where she and her co-authors argue that online communication networks uniquely enable marginalized populations to influence the terms and tone of mainstream public debate. Methodological contributions include techniques for the longitudinal analysis of communication networks using event-based network analysis, and guidelines for the effective use of network visualizations in scientific and lay publications. She has also contributed a number of critical pieces about computational methods and is the co-editor of a book on computational communication research entitled The Handbook of Networked Communication.

Foucault Welles’research is funded by grants from the US Army Research Office and US Army Research Lab,and has been featured in leading social science journals such as the Journal of Communication, New Media and Society, Information, Communication and Society, and The Annals of the American Academy of Political and Social Science. She serves on the editorial board of the journals Web Science and Social Media + Society. She earned her Ph.D. from the School of Communication at Northwestern University in Media, Technology, and Society, and undergraduate and M.S. degrees in Communication from Cornell University.

</p>

<br>

<br>
This week's suggested readings:

- `r readings1`
- `r readings2`

Additional readings:
- [Jackson, S. J., Bailey, M., & Welles, B. F. (2020). # HashtagActivism: Networks of Race and Gender Justice. MIT Press.](https://direct.mit.edu/books/book/4597/HashtagActivismNetworks-of-Race-and-Gender-Justice)

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
