---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "01/14/2021"
quarter <- "Winter2021"
week_folder <- "01-21_Kanich"
title <- "The Curse of Abundance: understanding and managing personal effects in the digital age"
speaker <- "Chris Kanich"
department <- "Department of Computer Science"
university <- "University of Illinois at Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2021/issues/2"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJEsde-prDgrH9ETnoaaKfrXSV5ejgbP6Ntu"
#Papers
week_paper_ref0 <- "Khan, M. T., Hyun, M., Kanich, C., & Ur, B. (2018, April). Forgotten but not gone: Identifying the need for longitudinal data management in cloud storage. In Proceedings of the 2018 CHI Conference on Human Factors in Computing Systems (pp. 1-12)."
week_paper_file0 <- "Khan_et_al(2018).pdf"



#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>


<p class=footertext2>

**Summary:** Modern digital systems enable the high fidelity retention of personal effects in quantities and timescales unimaginable even twenty years ago. While this capability is immensely beneficial for any number of reasons, the ability to accumulate these agglomerations are also embedded with risk. Modern ransomware and digital blackmail hint at the severity of this threat, but the full ramifications of our modern digital storage milieu is not well understood.

To characterize this phenomenon, we presented 100 online-survey participants with a stratified sample of 10 files currently stored in their own Dropbox or Google Drive accounts. We asked about the origin of each file, whether the participant remembered that file was stored there, and, when applicable, about that file’s sharing status. We also recorded participants’ preferences moving forward for keeping, deleting, or encrypting those files, as well as adjusting sharing settings. Participants had forgotten that half of the files they saw were in the cloud. Overall, 83% of participants wanted to delete at least one file they saw, while 13% wanted to unshare at least one file.

To begin to wrangle with these issues, we take a holistic approach to helping users identify sensitive and unwanted files in cloud storage. We first conducted 17 qualitative interviews to characterize factors that make humans perceive a file as sensitive, useful, and worthy of either protection or deletion. Building on our findings, we showed 108 long-term users of Google Drive or Dropbox a selection of files from their accounts. They labeled and explained these files' sensitivity, usefulness, and desired management (whether they wanted to keep, delete, or protect them). For each file, we collected many metadata and content features, building a training dataset of 3,525 labeled files. We then built Aletheia, which predicts a file's perceived sensitivity and usefulness, as well as its desired management. Aletheia improves over state-of-the-art baselines by 26% to 159%, predicting users' desired file-management decisions with 79% accuracy. Notably, predicting subjective perceptions of usefulness and sensitivity led to a 10% absolute accuracy improvement in predicting desired file-management decisions. Aletheia's performance validates a human-centric approach to feature selection when using inference techniques on subjective security-related tasks. It also improves upon the state of the art in minimizing the attack surface of cloud accounts.


</p>


<p class=footertext2>

**Chris Kanich** is an Associate Professor at the University of Illinois at Chicago in the Department of Computer Science. He conducts data-driven research on the socio-technical aspects of cybersecurity. This research includes characterizing the shifting long-term privacy needs of Internet users, better understanding the extent to which deep learning threatens user security and privacy on the web, as well as the practical impact of security-centric tools like Single Sign-On and VPNs for users and non-users alike. His current work includes analysis of gains and losses due to undesirable activity on the Internet, investigating human factors in effective Internet security mechanisms, and building new technological primitives with the goal of increasing the practical security and privacy of Internet users.
</p>

<br>

<p class=footertext2>
**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

<br>
This week's suggested readings:

- `r readings0`
- A draft of the paper which has been distributed to the MACSS listserv and is available by request from Sanja Miklin (smiklin@uchicago.edu). 

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
