---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "02/11/2021"
quarter <- "Winter2021"
week_folder <- "02-11_Starbird"
title <- "Online Rumors, Misinformation and Disinformation: The Perfect Storm of Covid-19"
speaker <- "Kate Starbird"
department <- "Department of Human Centered Design & Engineering"
university <- "University of Washington"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2021/issues/5"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJIoceyoqzkiH9JOwa8sPNoIhuGaxqVbAG7V"
#Papers
week_paper_ref1 <- "Maddock, J., Starbird, K., Al-Hassani, H. J., Sandoval, D. E., Orand, M., & Mason, R. M. (2015, February). Characterizing online rumoring behavior using multi-dimensional signatures. In Proceedings of the 18th ACM conference on computer supported cooperative work & social computing (pp. 228-241)."
week_paper_file1 <- "Maddock_et_al(2015).pdf"

week_paper_ref2 <- "Starbird, K.,Spiro, E., & West, J. (2020, May 9) This Covid-19 Misinformation Went Viral. Here's What We Learned. The Washington Post. Retrieved from www.washingtonpost.com/politics/2020/05/08/this-covid-19-misinformation-went-viral-heres-what-we-learned/"
week_paper_file2 <- "Starbird_et_al(2020).pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")
readings2 <- paste0("[", week_paper_ref2,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file2,")")
```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>
**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

<p class=footertext2>

**Summary:** The past year has been a difficult one. A pandemic has taken millions of lives and disrupted “normal” routines across the globe. In the United States, more than 450,000 lives have been lost, and some have pointed to rampant misinformation about Covid-19 as a potential factor in our country’s relatively poor response to the virus. Sociologists of disaster have long known that we are particularly vulnerable to the spread of misinformation during times of crisis — due to uncertainty in the information environment and anxiety about what the impacts will be and how we should respond. Covid-19 represents a perfect storm for misinformation, with persistent uncertainty surrounding the disease and the public increasingly relying on online information systems where misinformation is already pervasive. In this talk, I will demonstrate some of the ways that misinformation — and disinformation — about Covid-19 have spread through online spaces over the past year, demonstrating some of the structure and dynamics of this phenomenon. After laying out the problems, I aim to end on a more hopeful note, with a call to action for researchers and industry professionals to help “chip away” at this critical societal issue. 


</p>

<br>

<p class=footertext2>

**Kate Starbird** is an Associate Professor at the Department of Human Centered Design & Engineering (HCDE) at the University of Washington (UW). Kate’s research sits in the emerging field of crisis informatics—the study of how social media and other communication technologies are used during crisis events. Currently, her work focuses on the production and spread of online rumors, misinformation, and disinformation in the crisis context. Starbird is a co-founder of the UW Center for an Informed Public.
</p>

<br>

<br>
This week's suggested readings:

- Methodology: `r readings1`
- Content: `r readings2`

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
