---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "02/25/2021"
quarter <- "Winter2021"
week_folder <- "02-25_Bassett"
title <- "(In)citing Action to Realize an Equitable Future"
speaker <- "Danielle Bassett"
department <- "Departments of Bioengineering, Electrical & Systems Engineering, Physics & Astronomy, Neurology, and Psychiatry"
university <- "University of Pennsylvania"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2021/issues/7"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJYvceuuqjoqHtH22bdL00lvo29kz5gEmyy_"
#Papers
week_paper_ref1 <- "Dworkin, J. D., Linn, K. A., Teich, E. G., Zurn, P., Shinohara, R. T., & Bassett, D. S. (2020). The extent and drivers of gender imbalance in neuroscience reference lists. *Nature neuroscience*, 23(8), 918-926."
week_paper_file1 <- "Dworkin_et_al(2020).pdf"

week_paper_ref2 <- "Bertolero, M. A., Dworkin, J. D., David, S. U., Lloreda, C. L., Srivastava, P., Stiso, J., ... & Bassett, D. S. (2020 Preprint). Racial and ethnic imbalance in neuroscience reference lists and intersections with gender. *BioRxiv*."
week_paper_file2 <- "Bertolero_et_al(2020).pdf"

week_paper_ref3 <- "Dworkin, J., Zurn, P., & Bassett, D. S. (2020). (In) citing action to realize an equitable future. Neuron, 106(6), 890-894."
week_paper_file3 <- "Dworkin,Zurn&Bassett(2020).pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/main/",week_folder)

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/main/", week_folder,"/",week_paper_file1,")")


readings2 <- paste0("[", week_paper_ref2,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/main/", week_folder,"/",week_paper_file2,")")
readings3 <- paste0("[", week_paper_ref3,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/main/", week_folder,"/",week_paper_file3,")")
```






<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>
**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [**link**](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

<p class=footertext2>

**Summary:** In recent years, science has been pushed to grapple with the social and structural systems that produce vast gender and racial/ethnic imbalances in academic participation. While current discussions largely focus on the role of people in positions of power (e.g., journal editors, grant reviewers and agencies, department chairs, and society presidents), many imbalances are in fact caused and perpetuated by researchers themselves. A key example is imbalance within citation practices, where people from marginalized groups are broadly undercited, precluding an unbiased trajectory in the search for scientific truth. Because of the downstream effects that citations can have on visibility and career advancement, understanding and eliminating bias in citation practices is vital for addressing inequity in our scientific community. Here we uncover evidence of striking (and growing) gender and racial/ethnic imbalances in reference lists of STEM articles, and evaluate several candidate drivers of those imbalances. We also offer practical (and open-access) tools for the mitigation of disparity, thereby placing the power for social justice within the hands of individual researchers.

</p>

<br>

<p class=footertext2>

**Prof. Bassett** is the J. Peter Skirkanich Professor at the University of Pennsylvania, with appointments in the Departments of Bioengineering, Electrical & Systems Engineering, Physics & Astronomy, Neurology, and Psychiatry. Bassett is also an external professor of the Santa Fe Institute. Bassett is most well-known for blending neural and systems engineering to identify fundamental mechanisms of cognition and disease in human brain networks. Bassett is currently writing a book for MIT Press entitled *Curious Minds*, with co-author Perry Zurn Professor of Philosophy at American University. Bassett received a B.S. in physics from Penn State University and a Ph.D. in physics from the University of Cambridge, UK as a Churchill Scholar, and as an NIH Health Sciences Scholar. Following a postdoctoral position at UC Santa Barbara, Bassett was a Junior Research Fellow at the Sage Center for the Study of the Mind. Bassett has received multiple prestigious awards, including American Psychological Association's ‘Rising Star’ (2012), Alfred P Sloan Research Fellow (2014), MacArthur Fellow Genius Grant (2014), Early Academic Achievement Award from the IEEE Engineering in Medicine and Biology Society (2015), Harvard Higher Education Leader (2015), Office of Naval Research Young Investigator (2015), National Science Foundation CAREER (2016), Popular Science Brilliant 10 (2016), Lagrange Prize in Complex Systems Science (2017), Erdos-Renyi Prize in Network Science (2018), OHBM Young Investigator Award (2020), AIMBE College of Fellows (2020). Bassett is the author of more than 300 peer-reviewed publications, which have garnered over 27,000 citations, as well as numerous book chapters and teaching materials. Bassett is the founding director of the Penn Network Visualization Program, a combined undergraduate art internship and K-12 outreach program bridging network science and the visual arts. Bassett’s work has been supported by the National Science Foundation, the National Institutes of Health, the Army Research Office, the Army Research Laboratory, the Office of Naval Research, the Department of Defense, the Alfred P Sloan Foundation, the John D and Catherine T MacArthur Foundation, the Paul Allen Foundation, the ISI Foundation, and the Center for Curiosity.

</p>

<br>

<br>
This week's suggested readings:

- `r readings1`
- `r readings2`

Additional related reading:

- `r readings3`

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m.. All interested faculty and graduate students are welcome.</p>


<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
